# Example configuration for mm_reranker_eval

model:
  # Model name or path (required)
  # Can be:
  #   - Remote model name: jinaai/jina-reranker-m0, jinaai/jina-clip-v2, 
  #     lightonai/MonoQwen2-VL-v0.1, etc.
  #   - Absolute path: /path/to/local/model
  #   - Relative path: ./models/my-model
  # For local paths, model type is auto-detected from directory name or config.json
  # 
  # Note: Jina reranker and similar models require both query_type and doc_type
  # parameters. The framework automatically infers these from query/document modalities.
  name: jinaai/jina-reranker-m0
  
  # Device: 'cuda' or 'cpu' (default: cuda)
  device: cuda
  
  # Number of GPUs to use (default: auto-detect from CUDA_VISIBLE_DEVICES)
  num_gpus: null
  
  # Use flash attention 2 for better performance (requires compatible GPU)
  # Only applicable for jinaai/jina-reranker-m0
  use_flash_attention: true
  
  # Additional model-specific arguments
  # For jinaai/jina-clip-v2, you can specify:
  #   truncate_dim: 512  # Matryoshka dimension (None for full 1024-dim)
  kwargs: {}

data:
  # Path to evaluation data (JSONL file)
  eval_data_path: data/eval.jsonl
  
  # Path to candidate documents (JSONL file)
  candidate_docs_path: data/candidates.jsonl
  
  # Maximum number of queries to evaluate (null = all)
  max_queries: null
  
  # Base directory for image/video paths (optional)
  # If provided, relative paths in JSONL will be resolved relative to this directory
  base_dir: null  # e.g., "/path/to/images" or "./data/images"

metrics:
  # List of K values for Recall@K
  recall_k: [1, 3, 5, 7, 10]
  
  # List of K values for NDCG@K (null = not computed)
  ndcg_k: null

# Output directory for results
output_dir: results/experiment_001

# Additional arguments for rank() method
rank_kwargs:
  max_length: 2048

# Whether to save per-query results
save_per_query: false

# =============================================================================
# Alternative Model Configurations (Examples)
# =============================================================================

# --- GLM-4.1V-9B-Thinking Reranker ---
# Supports three scoring modes: logits_pyes, generative_ranking, listwise_scores
#
# model:
#   name: THUDM/GLM-4.1V-9B-Thinking
#   # or: zai-org/GLM-4.1V-9B-Thinking
#   device: cuda
#   kwargs:
#     scoring_mode: logits_pyes  # Options: logits_pyes, generative_ranking, listwise_scores
#     torch_dtype: bfloat16      # bfloat16 recommended for efficiency
#     max_new_tokens: 512        # For generative modes (generative_ranking, listwise_scores)
#
# Scoring modes explained:
#   - logits_pyes: Extract P(Yes) from Yes/No token logits (fast, efficient, similar to MonoQwen2-VL)
#   - generative_ranking: Generate ranking sequence like "1, 3, 2" (interpretable, flexible)
#   - listwise_scores: Generate score list like "0.95, 0.72, 0.83" (fine-grained control)

# --- MonoQwen2-VL Reranker ---
# model:
#   name: lightonai/MonoQwen2-VL-v0.1
#   device: cuda
#   kwargs:
#     torch_dtype: bfloat16
#     attn_implementation: flash_attention_2

# --- BGE-VL-MLLM Reranker ---
# model:
#   name: BAAI/BGE-VL-MLLM-S1
#   device: cuda
# rank_kwargs:
#   instruction: "Retrieve relevant documents for the query."

# --- Jina CLIP v2 ---
# model:
#   name: jinaai/jina-clip-v2
#   device: cuda
#   kwargs:
#     truncate_dim: 512  # Matryoshka dimension (None for full 1024-dim)

