# Example configuration for mm_reranker_eval

model:
  # Model name or path (required)
  # Can be:
  #   - Remote model name: jinaai/jina-reranker-m0
  #   - Absolute path: /path/to/local/model
  #   - Relative path: ./models/my-model
  # For local paths, model type is auto-detected from directory name or config.json
  # 
  # Note: Jina reranker and similar models require both query_type and doc_type
  # parameters. The framework automatically infers these from query/document modalities.
  name: jinaai/jina-reranker-m0
  
  # Device: 'cuda' or 'cpu' (default: cuda)
  device: cuda
  
  # Number of GPUs to use (default: auto-detect from CUDA_VISIBLE_DEVICES)
  num_gpus: null
  
  # Use flash attention 2 for better performance (requires compatible GPU)
  use_flash_attention: true
  
  # Additional model-specific arguments
  kwargs: {}

data:
  # Path to evaluation data (JSONL file)
  eval_data_path: data/eval.jsonl
  
  # Path to candidate documents (JSONL file)
  candidate_docs_path: data/candidates.jsonl
  
  # Maximum number of queries to evaluate (null = all)
  max_queries: null
  
  # Base directory for image/video paths (optional)
  # If provided, relative paths in JSONL will be resolved relative to this directory
  base_dir: null  # e.g., "/path/to/images" or "./data/images"

metrics:
  # List of K values for Recall@K
  recall_k: [1, 3, 5, 7, 10]
  
  # List of K values for NDCG@K (null = not computed)
  ndcg_k: null

# Output directory for results
output_dir: results/experiment_001

# Additional arguments for rank() method
rank_kwargs:
  max_length: 2048

# Whether to save per-query results
save_per_query: false

